# html lang
language: en

menuname: Tanger's blog

# main menu navigation
menu1:
  å…³äºæˆ‘ğŸ‘€: /about
  è®¿é—®ä¸»ç«™ğŸ‰: https://liuxunzhuo.tech
  GitHubğŸ’: https://github.com/xunzhuo

menu:
  é¦–é¡µ: /
  å…³äº: /about
# blogå¤´åƒ
img_src: https://avatars.githubusercontent.com/u/57751257?v=4
# ç½‘ç«™æ ‡é¢˜ | Title
logo_title: Hexo Theme
#æ ‡è¯­ | Your Slogan
words: Your Words

# ä½ çš„æ˜µç§° | Your Name
author: Your Name

# æ»‘åŠ¨é¡¶éƒ¨æ¡†
topmenu:
  é¦–é¡µ  index: /
  å…³äº  about: /about

# stylesheets loaded in the <head>
stylesheets:
  - /css/MiHoYo.css

# scripts loaded in the end of the body
scripts:
  - /js/MiHoYo.js

# è¯„è®ºç³»ç»Ÿ | Comments
## åšäº†åŸŸåé™åˆ¶ï¼Œè¯·æ”¹æˆè‡ªå·±çš„ KEY
## è‹¥å…³é—­valine è®¾ç½®enableä¸ºfalseâˆ‚
valine:
  enable: true
  appId: 
  appKey: 
